[package]
name = "dnp3-schema"
# this version is what gets applied to the FFI libraries
version = "1.4.0-rc1"
authors = ["Step Function I/O LLC <info@stepfunc.io>"]
edition = "2021"

[dependencies]
oo-bindgen = "0.8"
sfio-tracing-ffi = "0.8"
sfio-tokio-ffi = "0.8"
