[package]
name = "dnp3-schema"
version = "1.0.0-rc2"
authors = ["Émile Grégoire <emile@stepfunc.io>"]
edition = "2021"

[dependencies]
dnp3 = { path = "../../dnp3" }
oo-bindgen = { git = "https://github.com/stepfunc/oo_bindgen.git", branch = "feature/c++" }
