[package]
name = "dnp3-schema"
version = "0.1.0"
authors = ["Émile Grégoire <emile@automatak.com>"]
edition = "2018"

[dependencies]
dnp3 = { path = "../../dnp3" }
oo-bindgen = { git = "https://git@github.com/stepfunc/oo_bindgen.git", branch = "feature/ci-update" }
