[package]
name = "dnp3-bindings"
version = "0.1.0"
authors = ["Émile Grégoire <emile@automatak.com>"]
edition = "2018"

[dependencies]
ci-script = { git = "https://git@github.com/grid-io/oo_bindgen.git", branch="java-jni" }
dnp3-schema = { path = "../dnp3-schema" }
dnp3-ffi = { path = "../dnp3-ffi" }
