[package]
name = "dnp3-bindings"
version = "1.0.0-rc2"
authors = ["Émile Grégoire <emile@stepfunc.io>"]
edition = "2021"

[dependencies]
ci-script = { git = "https://github.com/stepfunc/oo_bindgen.git", branch = "feature/c++" }
dnp3-schema = { path = "../dnp3-schema" }
dnp3-ffi = { path = "../dnp3-ffi" }
